[package]
name = "c1_sensors"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m-rt = "0.7.5"
heapless = "0.8.0"
lsm303agr = "1.1.0"
microbit-v2 = "0.15.1"
panic-halt = "1.0.0"

[dependencies.serial_utils]
version = "0.1.0"
path = "../serial_utils"
